# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-66557167-1"

# UI configs
title: "Astrophotography by Mati Bot"
subtitle: "Connect with the universe through photos"
author: "Mati Bot"
header:
 title: "Astrophotography"
 subtitle: "by Mati Bot"
footer:
 name: "Hi, I'm Mati"
 bio: "Software Engineer by day, Astrophotographer by night."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/matib"
  twitter: "https://www.twitter.com/b0tnik"
  instagram: "https://www.instagram.com/matibot"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/matibot"
  github: "https://www.github.com/matibot"
